In [1]:
!pip install numpy

In [2]:
import numpy as np

# creating numpy array

### single dimensional array

In [3]:
n1=np.array([10,20,30,40,50])

In [4]:
n1

array([10, 20, 30, 40, 50])

In [5]:
type(n1)

numpy.ndarray

### multi dimensional array

In [6]:
n2=np.array([[10,20,30,40],[50,60,70,80]])

In [7]:
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
type(n2)

numpy.ndarray

# initializing numpy array

### initializing numpy array with zeros

In [9]:
n1=np.zeros((1,2))

In [10]:
n1

array([[0., 0.]])

In [11]:
n1=np.zeros((5,5))

In [12]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
type(n1)

numpy.ndarray

### initializing numpy array with same numbers 

In [14]:
n1=np.full((3,3),10)

In [15]:
n1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
n1=np.full((3,3),12)

In [17]:
n1

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [18]:
n1=np.full((4,10),10)

In [19]:
n1

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

###  initializing numpy array with arange

In [20]:
n1=np.arange(10,99)

In [21]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98])

##### with gap 

In [22]:
n1=np.arange(10,50,5)

In [23]:
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

### initializing numpy array with random number

In [24]:
n1=np.random.randint(1,100,5)

In [25]:
n1

array([44, 50, 70, 93, 12])

# numpy shape

In [26]:
n2=np.array([[10,20,30,40],[50,60,70,80]])

In [27]:
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [28]:
n2.shape

(2, 4)

### change shape

In [29]:
n2.shape=(4,2)

In [30]:
n2

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

# joining numpy arrays

In [31]:
n1=np.array([10,20,30,40,50])

In [32]:
n2=np.array([60,70,80,90,99])

### vertically join

In [33]:
np.vstack((n1,n2))

array([[10, 20, 30, 40, 50],
       [60, 70, 80, 90, 99]])

### horizontaly join

In [34]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 99])

###  column join

In [35]:
np.column_stack((n1,n2))

array([[10, 60],
       [20, 70],
       [30, 80],
       [40, 90],
       [50, 99]])

# numpy intersection & difference

In [36]:
n1=np.array([10,20,30,40,50])

In [37]:
n2=np.array([10,25,62,40])

In [39]:
np.setdiff1d(n1,n2)

array([20, 30, 50])

In [43]:
np.setdiff1d(n2,n1)

array([25, 62])

In [44]:
np.intersect1d(n1,n2)

array([10, 40])

In [45]:
np.intersect1d(n2,n1)

array([10, 40])